Update promote_package.yml

diff --git a/.github/workflows/promote_package.yml b/.github/workflows/promote_package.yml
--- a/.github/workflows/promote_package.yml
+++ b/.github/workflows/promote_package.yml
@@ -49,9 +49,22 @@ jobs:
           
           echo "Found package identifier: $IDENTIFIER"
           cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ready-for-production
+
+          # Retrieve all packages with the 'ready-for-production' tag
+          PACKAGE_DATA_PRODUCTION_READY=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} --tag ready-for-production -F json)
+          
+          # Extract the identifier_perm for ready-for-production tag packages
+          IDENTIFIER_PRODUCTION_READY=$(echo "$PACKAGE_DATA_PRODUCTION_READY" | jq -r '.data[0].identifier_perm')
+          
+          if [ -z "$IDENTIFIER_PRODUCTION_READY" ] || [ "$IDENTIFIER_PRODUCTION_READY" = "null" ]; then
+            echo "Failed to find package identifier"
+            exit 1
+          fi
+          
+          echo "Found package identifier: $IDENTIFIER_PRODUCTION_READY"
           
           # Promote package using the identifier
           cloudsmith mv --yes \
-            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
+            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER_PRODUCTION_READY \
             ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
         shell: bash
